-- =====================================================================
-- My Hidden Story — initial schema
-- 2026-04-26
--
-- Three tables:
--   quiz_sessions  : one row per visitor, captures quiz answers + funnel events
--   stories        : one row per generated story (the "story bible")
--   chapters       : one row per chapter; holds the chapter text, the 3
--                    options for the next chapter, and (once chosen) which
--                    option the user picked.
--
-- Design choices:
--   * UUID primary keys generated by gen_random_uuid() unless the client
--     supplies one (so the existing client-side ss_session UUID is reusable).
--   * Mutable per-chapter context (story bible, world state, etc.) lives in
--     a JSONB `state` column so prompt evolution doesn't require migrations.
--   * RLS is on for every table with NO public policies, so only the service
--     role (used inside edge functions) can read/write. Frontend talks to
--     edge functions, never directly to the DB.
-- =====================================================================

-- --- helper: auto-update updated_at on UPDATE ---------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- =====================================================================
-- quiz_sessions
-- =====================================================================
create table if not exists public.quiz_sessions (
  id                  uuid primary key default gen_random_uuid(),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- contact + funnel state
  email               text,
  email_captured_at   timestamptz,
  paid                boolean      not null default false,
  payment_at          timestamptz,
  plan                text,                -- '1' | '4' | '8'
  status              text         not null default 'open',  -- open | email_captured | paid | converted | abandoned

  -- quiz answers (single-select)
  q_character         text,
  q_feeling           text,
  q_fantasy           text,
  q_power             text,
  q_emotion           text,
  q_start             text,
  q_missing           text,
  q_romance_type      text,
  q_experience        text,
  q_reason            text,

  -- multi-select (joined with "||" on the wire, stored as array here)
  q_spicy_trigger     text[],

  -- progressive yes/no
  q_intense           text,
  q_explicit          text,
  q_explore           text,
  q_relationship      text,

  -- attribution / device
  fbclid              text,
  fbc                 text,
  funnel_version      text,
  landing_page        text,
  user_agent          text,
  device_type         text
);

create index if not exists quiz_sessions_email_idx       on public.quiz_sessions (email);
create index if not exists quiz_sessions_created_at_idx  on public.quiz_sessions (created_at desc);
create index if not exists quiz_sessions_status_idx      on public.quiz_sessions (status);

drop trigger if exists trg_quiz_sessions_set_updated_at on public.quiz_sessions;
create trigger trg_quiz_sessions_set_updated_at
  before update on public.quiz_sessions
  for each row execute function public.set_updated_at();


-- =====================================================================
-- stories
-- =====================================================================
create table if not exists public.stories (
  id                       uuid primary key default gen_random_uuid(),
  session_id               uuid not null references public.quiz_sessions(id) on delete cascade,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  lead_email               text not null,
  status                   text not null default 'pending',
  -- pending | chapter_1_generating | active | completed | error

  target_chapter_count     int  not null default 10,
  current_chapter_number   int  not null default 0,

  -- structured story metadata extracted from chapter 1
  title                    text,
  genre                    text,
  tone_label               text,
  heat_level               text,
  setting_type             text,
  fantasy_type             text,
  relationship_dynamic     text,
  character_archetype      text,
  hook                     text,
  opening_premise          text,
  original_setup           text,

  -- Mutable continuity context the AI needs each chapter.
  -- Keys: global_summary, story_bible_summary, world_rules, world_state,
  -- character_state, relationship_map, timeline_state, open_loops,
  -- resolved_loops, items_of_importance, secrets_and_reveals
  state                    jsonb not null default '{}'::jsonb,

  -- last error from the AI / parser (so retries can inspect it)
  last_error               text
);

create index if not exists stories_session_id_idx  on public.stories (session_id);
create index if not exists stories_lead_email_idx  on public.stories (lead_email);
create index if not exists stories_status_idx      on public.stories (status);
create index if not exists stories_created_at_idx  on public.stories (created_at desc);

drop trigger if exists trg_stories_set_updated_at on public.stories;
create trigger trg_stories_set_updated_at
  before update on public.stories
  for each row execute function public.set_updated_at();


-- =====================================================================
-- chapters
-- =====================================================================
create table if not exists public.chapters (
  id                  uuid primary key default gen_random_uuid(),
  story_id            uuid not null references public.stories(id) on delete cascade,
  chapter_number      int  not null check (chapter_number between 1 and 50),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- content
  text                text not null,
  summary             text,
  mood                text,
  key_event           text,
  closure_hook        text,

  -- planned trajectory for the NEXT chapter, set when this chapter is generated
  next_chapter_goal           text,
  next_chapter_arc_position   text,
  next_chapter_tone_hint      text,
  next_chapter_stakes_level   text,

  -- 3 options the user can pick to continue
  option_1            text,
  option_2            text,
  option_3            text,

  -- once the user clicks an email link, we record their pick here
  chosen_option       int  check (chosen_option in (1, 2, 3)),
  chosen_at           timestamptz,

  -- email delivery
  email_sent_at       timestamptz,

  unique (story_id, chapter_number)
);

create index if not exists chapters_story_id_idx           on public.chapters (story_id);
create index if not exists chapters_chosen_option_idx      on public.chapters (story_id, chapter_number) where chosen_option is not null;

drop trigger if exists trg_chapters_set_updated_at on public.chapters;
create trigger trg_chapters_set_updated_at
  before update on public.chapters
  for each row execute function public.set_updated_at();


-- =====================================================================
-- RLS — locked down by default. Only the service role (used inside edge
-- functions) can read/write. Frontend calls edge functions, never the DB.
-- =====================================================================
alter table public.quiz_sessions enable row level security;
alter table public.stories       enable row level security;
alter table public.chapters      enable row level security;

-- Intentionally no policies for anon / authenticated.
-- The service role bypasses RLS automatically.
